import * as tokens from '@covalent/tokens';

export const cvEditorDarkTheme = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    {
      token: '',
      foreground: tokens.CvDarkCodeSnippetColor,
      background: tokens.CvThemeDarkColorsSurface,
    },
    {
      token: 'comment',
      foreground: tokens.CvDarkCodeSnippetComment,
      fontStyle: 'italic',
    },
    { token: 'keyword', foreground: tokens.CvDarkCodeSnippetKeyword },
    { token: 'variable', foreground: tokens.CvDarkCodeSnippetVariable },
    { token: 'string', foreground: tokens.CvDarkCodeSnippetString },
    { token: 'number', foreground: tokens.CvDarkCodeSnippetVariable },
    { token: 'type', foreground: tokens.CvDarkCodeSnippetClass },
    { token: 'class', foreground: tokens.CvDarkCodeSnippetClass },
    { token: 'function', foreground: tokens.CvDarkCodeSnippetTitle },
    { token: 'operator', foreground: tokens.CvDarkCodeSnippetLiteral },
    { token: 'constant', foreground: tokens.CvDarkCodeSnippetLiteral },
    { token: 'builtin', foreground: tokens.CvDarkCodeSnippetClass },
    { token: 'punctuation', foreground: tokens.CvDarkCodeSnippetColor },
    { token: 'meta', foreground: tokens.CvDarkCodeSnippetTitle },
    { token: 'tag', foreground: tokens.CvDarkCodeSnippetSelector },
    { token: 'attribute.name', foreground: tokens.CvDarkCodeSnippetVariable },
    { token: 'attribute.value', foreground: tokens.CvDarkCodeSnippetString },
    { token: 'invalid', foreground: '#f44747' },
    { token: 'strong', fontStyle: 'bold' },
    { token: 'emphasis', fontStyle: 'italic' },
    {
      token: 'link',
      foreground: tokens.CvDarkCodeSnippetTitle,
      fontStyle: 'underline',
    },
  ],
  colors: {
    'editor.background': tokens.CvThemeDarkColorsSurface,
    'editor.foreground': tokens.CvDarkCodeSnippetColor,
    'editorCursor.foreground': tokens.CvDarkTextSecondaryOnBackground,
  },
};

export const cvEditorLightTheme = {
  base: 'vs',
  inherit: true,
  rules: [
    {
      token: '',
      foreground: tokens.CvLightCodeSnippetColor,
      background: tokens.CvLightSurfaceCanvas,
    },
    {
      token: 'comment',
      foreground: tokens.CvLightCodeSnippetComment,
      fontStyle: 'italic',
    },
    { token: 'keyword', foreground: tokens.CvLightCodeSnippetKeyword },
    { token: 'doctag', foreground: tokens.CvLightCodeSnippetKeyword },
    { token: 'formula', foreground: tokens.CvLightCodeSnippetKeyword },
    { token: 'variable', foreground: tokens.CvLightCodeSnippetVariable },
    { token: 'string', foreground: tokens.CvLightCodeSnippetString },
    { token: 'number', foreground: tokens.CvLightCodeSnippetVariable },
    { token: 'type', foreground: tokens.CvLightCodeSnippetClass },
    { token: 'class', foreground: tokens.CvLightCodeSnippetClass },
    { token: 'function', foreground: tokens.CvLightCodeSnippetTitle },
    { token: 'literal', foreground: tokens.CvLightCodeSnippetLiteral },
    { token: 'operator', foreground: tokens.CvLightCodeSnippetLiteral },
    { token: 'constant', foreground: tokens.CvLightCodeSnippetLiteral },
    { token: 'builtin', foreground: tokens.CvLightCodeSnippetClass },
    { token: 'punctuation', foreground: tokens.CvLightCodeSnippetColor },
    { token: 'meta', foreground: tokens.CvLightCodeSnippetTitle },
    { token: 'tag', foreground: tokens.CvLightCodeSnippetSelector },
    { token: 'attribute.name', foreground: tokens.CvLightCodeSnippetVariable },
    { token: 'attribute.value', foreground: tokens.CvLightCodeSnippetString },
    { token: 'invalid', foreground: '#f44747' },
    { token: 'strong', fontStyle: 'bold' },
    { token: 'emphasis', fontStyle: 'italic' },
    {
      token: 'link',
      foreground: tokens.CvLightCodeSnippetTitle,
      fontStyle: 'underline',
    },
  ],
  colors: {
    'editor.background': tokens.CvThemeLightColorsSurface,
    'editor.foreground': tokens.CvLightCodeSnippetColor,
    'editorCursor.foreground': tokens.CvLightTextSecondaryOnBackground,
  },
};
