#!/usr/bin/env bash
set -e

# clean up first if building again
rm -rf ./src/platform/node_modules
rm -rf ./deploy

# BUILD: @covalent/core primary entrypoint
./node_modules/@angular/cli/bin/ng build covalent-core

echo 'Compiling and moving moving some requried files not handled by ng-packagr'
gulp move-required-core-files
gulp compile-core-sass
echo 'Completed compiling and moving moving some requried files not handled by ng-packagr'

# HACK (Remove in future): used to resolve ng-packagr current lack of support for Intra-package dependencies between primary entry points
# HACK START
mkdir -p src/platform/node_modules/@covalent
cp -r deploy/platform/core src/platform/node_modules/@covalent
# HACK END

# BUILD: @covalent/dynamic-forms primary entrypoint
./node_modules/@angular/cli/bin/ng build covalent-dynamic-forms
# BUILD: @covalent/highlight primary entrypoint
./node_modules/@angular/cli/bin/ng build covalent-highlight
# BUILD: @covalent/http primary entrypoint
./node_modules/@angular/cli/bin/ng build covalent-http
# BUILD: @covalent/markdown primary entrypoint
./node_modules/@angular/cli/bin/ng build covalent-markdown
# BUILD: @covalent/code-editor primary entrypoint
./node_modules/@angular/cli/bin/ng build covalent-code-editor
# BUILD: @covalent/text-editor primary entrypoint
./node_modules/@angular/cli/bin/ng build covalent-text-editor
# BUILD: @covalent/echarts primary entrypoint
./node_modules/@angular/cli/bin/ng build covalent-echarts

# HACK (Remove in future): used to resolve ng-packagr current lack of support for Intra-package dependencies between primary entry points
# HACK START
cp -r deploy/platform/markdown src/platform/node_modules/@covalent
cp -r deploy/platform/highlight src/platform/node_modules/@covalent
cp -r deploy/platform/http src/platform/node_modules/@covalent
# HACK END

# BUILD: @covalent/flavored-markdown primary entrypoint
./node_modules/@angular/cli/bin/ng build covalent-flavored-markdown

# HACK (Remove in future): used to resolve ng-packagr current lack of support for Intra-package dependencies between primary entry points
# Help module within experimental depends on flavored-markdown
# HACK START
cp -r deploy/platform/flavored-markdown src/platform/node_modules/@covalent
# HACK END

# BUILD: @covalent/experimental primary entrypoint
./node_modules/@angular/cli/bin/ng build covalent-experimental

# HACK (Remove in future): remove remnants of platform/node_modules was used for building purposes
rm -rf src/platform/node_modules

# BUILD: Schematics
gulp build-schematics-assets

# Need to move required file after ng-packagr runs because ng-packagr overrides primary entrypoint folders
gulp move-additional-platform-files
