#!/bin/bash

set -o errexit

# Clear deploy/ so that we guarantee there are no stale artifacts.
echo "Cleaning deploy/"
rm -rf ./deploy

# Perform a build.
gulp build
echo "SASS compiled..."

# Prepare for aot
gulp prepare-aot
echo "Preparing files for AoT build"

# Run build
ng build

# copy dist into deploy
cp -rf dist/ deploy/editor/

# copy package.json into deploy
cp -rf package.json deploy/editor/

# copy README.md into deploy
cp -rf README.md deploy/editor/

# AoT compilation
npm run aot
echo "Compiled TS and generated *.metadata.json files..."

# Inline the css and html into the component files.
gulp inline-resource-files
echo "Resources inlined..."

# Bundle
gulp rollup-code
echo "Bundled..."
