#!/bin/bash
version=$1

set -e

echo "Finished release v$version"
git flow release finish v$version

echo "Pushed tag v$version to main repo"
git push --tags

echo "Pushing changes into develop"
git push origin develop

echo "Pushing changes into master"
git push origin master

echo "Building master branch"
npm run build

echo "Publishing master branch"
npm run publish

echo "Return to develop branch"
git checkout develop