#!/bin/bash
version=$1
storybook_dir="docs"

git remote set-url origin https://$GITHUB_TOKEN@github.com/Teradata/covalent.git

echo "Checking out gh-pages branch"
git fetch
git checkout gh-pages

echo "Created or replaced $version dir"
rm -rf ./$version
mkdir $version
cp -r dist/apps/docs-app/* $version

if [ "$DEPLOY_STORYBOOK" = "true" ]; then
  echo "Create or replace storybook dir"
  rm -rf ./$storybook_dir
  mkdir -p $storybook_dir
  cp -r ./dist/storybook/* ./$storybook_dir/
fi

echo "Configuring GIT User"
git config user.name github-actions
git config user.email github-actions@github.com

echo 'Tracking files'
git add -A $version
if [ "$DEPLOY_STORYBOOK" = "true" ]; then
  git add -A $storybook_dir
fi
echo 'Commiting files'
if [ "$DEPLOY_STORYBOOK" = "true" ]; then
  git commit --no-verify -a -m "feat(): gh-pages update for $version; update storybook pages"
else
  git commit --no-verify -a -m "feat(): gh-pages update for $version"
fi
echo 'Pushing files into gh-pages branch'
git push origin gh-pages --force
