#!/bin/bash
version=$1

echo "Checking out gh-pages branch"
git branch -f gh-pages
git checkout gh-pages

git reset --hard origin/develop

echo "Created or replaced $version dir"
rm -rf ./$version
mkdir $version
cp -r dist/covalent-docs/* $version

echo 'Tracking files'
git add -A $version
echo 'Commiting files'
git commit --no-verify -a -m "feat(): gh-pages update for $version"
echo 'Pushing files into gh-pages branch'
git push origin gh-pages --force