#!/bin/bash

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -e|--entrypoint)
    ENTRYPOINT="$2"
    shift # past argument
    shift # past value
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters
if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 "$1"
fi

set -o errexit -o nounset

if [ $ENTRYPOINT = "core" ]
then
  buildDir="deploy/platform/core"
  repoName="covalent-nightly"
  repoUrl="https://github.com/Teradata/covalent-nightly.git"
elif [ $ENTRYPOINT = "experimental" ]
then
  buildDir="deploy/platform/experimental"
  repoName="covalent-experimental-nightly"
  repoUrl="https://github.com/Teradata/covalent-experimental-nightly.git"
fi


commitSha=$(git rev-parse --short HEAD)
commitAuthorName=$(git --no-pager show -s --format='%an' HEAD)
commitAuthorEmail=$(git --no-pager show -s --format='%ae' HEAD)
commitMessage=$(git log --oneline -n 1)

repoDir="deploy/$repoName"

echo "Cloning $repoUrl into $repoDir"
git clone $repoUrl $repoDir

echo "Cleaning nightly repo and moving release files into it"
rm -rf $repoDir/*
cp -rf $buildDir/* $repoDir
cd $repoDir

# Prepare Git for pushing the artifacts to the repository.

git config user.name "$commitAuthorName"
git config user.email "$commitAuthorEmail"
git config credential.helper "store --file=.git/credentials"

echo "https://${COVALENT_NIGHTLY_TOKEN}:@github.com" > .git/credentials

git add -A
git commit -m "$commitMessage"
git tag "$commitSha"
git push origin master --tags

echo "Finished publishing nightly build"
