#!/bin/bash

echo "Building branch for night release"
#npm run build

set -o errexit -o nounset

if [ "$TRAVIS_BRANCH" != "master" ]
then
  echo "This commit was made against the $TRAVIS_BRANCH and not the master! No deploy!"
  exit 0
fi

if [ "$TRAVIS_BRANCH" == "master" ]
then
  echo "This commit was made against master! deploy!"
  exit 0
fi