#!/bin/bash
set -e

VERSION=${1:-0.0.0}

echo "Bumping @covalent package"

if [ "$VERSION" == "0.0.0" ] 
  then
  echo 'Version is not correctly set' >&2
  exit 1
fi

npm version ${VERSION} --no-git-tag-version
echo "Versioned ${package} successfully"

exit 0