#!/bin/bash
scope=@covalent/editor

#login into private registry
npm login --scope=$scope

npm publish ./deploy/editor/ --access=public

#logout when finished
npm logout 
echo "Published successfully [scope: $scope]. Use 'npm install [package-name]' in the project you want to use it."
