#!/bin/bash
registry=http://10.25.209.208:8080/
scope=@covalent

#login into private registry
npm login --registry=$registry --scope=$scope

for package in ./deploy/platform/*
do
  npm publish ${package}
done

#logout when finished
npm logout --registry=$registry
echo "Published successfully [registry: $registry, scope: $scope]. Use 'npm install [package-name]' in the project you want to use it."
echo "NOTE. You have to be logged in into the enterprise registry: $registry."
