#!/usr/bin/env bash

rm -rf ./dist

# Steps to package '@covalent/core' and it's children '@covalent/core/*'
npm run ng-packagr-core
# move over styles manually ng-packagr doesn't do it automatically
cp -r ./src/platform/core/common/styles ./dist/core/common
cp ./src/platform/core/common/_common-theme.scss ./dist/core/common
cp ./src/platform/core/common/material-icons.scss ./dist/core/common
cp ./src/platform/core/common/platform.scss ./dist/core/common
gulp compile-common-sass
