#!/bin/bash
version=$1
bump=$2

set -e

echo "Started release $version"

git flow release start $version develop

gulp bump-version --ver ${bump}

git add -A .

git commit -a -m "Version bump"

echo "Publishing release $version"
git flow release publish $version

echo "Executed unit tests"
npm run test