import { routeBuilder, IScopedRouteBuilder } from 'app/utilities/route-builder';

export const echartsRoutesCategories = [
  { name: '', nested: false },
  { name: 'Base', nested: false },
  { name: 'Chart Types', nested: false, color: 'blue-800' },
  { name: 'Atomic Components', nested: false, color: 'orange-A400' },
];

const [root, base, chartTypes, atomic] = echartsRoutesCategories;

export const echartsContentDetails: any = [
  {
    name: 'Bar',
    id: 'bar',
    description: '',
    apiDocUrl: 'platform/echarts/base/README.md',
    showExampleTab: true,
    showOverviewDemo: false,
    showOverview: true,
    hideOverview: false,
    category: chartTypes.name,
    overviewDocUrl: '',
    icon: 'insert_chart',
    route: '/echarts/bar',
  },
  {
    name: 'Chart',
    id: 'chart',
    description: 'Base component that instantiates an echarts object',
    apiDocUrl: 'platform/echarts/base/README.md',
    showExampleTab: true,
    showOverviewDemo: false,
    hideOverview: true,
    overviewDocUrl: '',
    icon: 'multiline_chart',
    category: base.name,
    route: '/echarts/chart',
    color: '',
  },
  {
    name: 'Combination',
    id: 'combination',
    description: '',
    apiDocUrl: 'platform/core/breadcrumbs/README.md',
    showExampleTab: true,
    showOverviewDemo: true,
    overviewDocUrl: '',
    icon: 'show_chart',
    hideOverview: false,
    category: chartTypes.name,
    route: '/echarts/combination',
    color: '',
  },
  {
    name: 'Graph',
    id: 'graph',
    description: '',
    apiDocUrl: 'platform/echarts/graph/README.md',
    showExampleTab: true,
    showOverviewDemo: true,
    overviewDocUrl: '',
    icon: 'grain',
    hideOverview: false,
    category: chartTypes.name,
    route: '/echarts/graph',
    color: '',
  },
  {
    name: 'Line',
    id: 'line',
    description: '',
    apiDocUrl: 'platform/echarts/line/README.md',
    showExampleTab: true,
    showOverviewDemo: true,
    overviewDocUrl: '',
    icon: 'bubble_chart',
    hideOverview: false,
    category: chartTypes.name,
    route: '/echarts/line',
    color: '',
  },
  {
    name: 'Pie',
    id: 'pie',
    description: '',
    apiDocUrl: 'platform/echarts/bar/README.md',
    showExampleTab: true,
    showOverviewDemo: true,
    hideOverview: false,
    category: chartTypes.name,
    overviewDocUrl: '',
    icon: 'insert_chart',
    route: '/echarts/pie',
  },
  {
    name: 'Sankey',
    id: 'sankey',
    description: '',
    apiDocUrl: 'platform/echarts/sankey/README.md',
    showExampleTab: true,
    showOverviewDemo: true,
    overviewDocUrl: '',
    icon: 'call_split',
    hideOverview: false,
    category: chartTypes.name,
    route: '/echarts/sankey',
    color: '',
  },
  {
    name: 'Scatter',
    id: 'scatter',
    description: '',
    apiDocUrl: 'platform/echarts/scatter/README.md',
    showExampleTab: true,
    showOverviewDemo: true,
    overviewDocUrl: '',
    icon: 'multiline_chart',
    hideOverview: false,
    category: chartTypes.name,
    route: '/echarts/scatter',
    color: '',
  },
  {
    name: 'Tree',
    id: 'tree',
    description: '',
    apiDocUrl: 'platform/echarts/tree/README.md',
    showExampleTab: true,
    showOverviewDemo: true,
    overviewDocUrl: '',
    icon: 'share',
    hideOverview: false,
    category: chartTypes.name,
    route: '/echarts/tree',
    color: '',
  },
  {
    name: 'Treemap',
    id: 'treemap',
    description: '',
    apiDocUrl: 'platform/echarts/treemap/README.md',
    showExampleTab: true,
    showOverviewDemo: true,
    overviewDocUrl: '',
    icon: 'dashboard',
    hideOverview: false,
    category: chartTypes.name,
    route: '/echarts/treemap',
    color: '',
  },
  {
    name: 'Axis',
    id: 'axis',
    description: '',
    apiDocUrl: 'platform/echarts/base/axis/README.md',
    showExampleTab: true,
    showOverviewDemo: true,
    overviewDocUrl: '',
    icon: 'trending_flat',
    hideOverview: true,
    category: atomic.name,
    route: '/echarts/axis',
    color: '',
  },
  {
    name: 'Dataset',
    id: 'dataset',
    description: '',
    apiDocUrl: 'platform/echarts/base/dataset/README.md',
    showExampleTab: true,
    showOverviewDemo: true,
    overviewDocUrl: '',
    icon: 'view_list',
    hideOverview: true,
    category: atomic.name,
    route: '/echarts/dataset',
    color: '',
  },
  {
    name: 'Tooltip',
    id: 'tooltip',
    description: '',
    apiDocUrl: 'platform/echarts/tooltip/README.md',
    showExampleTab: true,
    showOverviewDemo: true,
    overviewDocUrl: '',
    icon: 'info',
    hideOverview: true,
    category: atomic.name,
    route: '/echarts/tooltip',
    color: '',
  },
  {
    name: 'Toolbox',
    id: 'toolbox',
    description: '',
    apiDocUrl: 'platform/echarts/toolbox/README.md',
    showExampleTab: true,
    showOverviewDemo: true,
    overviewDocUrl: '',
    icon: 'art_track',
    hideOverview: true,
    category: atomic.name,
    route: '/echarts/toolbox',
    color: '',
  },
];

export const setEchartRoutes: IScopedRouteBuilder = routeBuilder(echartsContentDetails);
