name: Deploy

on:
  push:
    branches: [feat/knapsack]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'covalent-workspace' #Must be unique in Heroku
          heroku_email: '{{secrets.HEROKU_EMAIL}}'
          usedocker: true
