name: Generate design tokens

on:
  push:
    branches: [main]
    paths:
      - 'libs/tokens/src/**'

jobs:
  release:
    name: Generate Tokens
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_GH }}
          persist-credentials: false
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npx ci
      - name: Generate design tokens and commit
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GH }}
        run: npm run tokens:generate
